[tool.poetry]
name = "mypypi"
version = "0.1.0"
description = ""
authors = ["daniilbelov"]
readme = "README.md"
packages = [{include = "service"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

